### ISSUE TITLE
Define & implement desired JavaScript linter for Pressbooks

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/coding-standards#11]
We currently import and use HumanMade's ESLint (https://github.com/humanmade/coding-standards/tree/master/packages/eslint-config-humanmade) in our coding standards and build tools: https://github.com/pressbooks/pressbooks-build-tools/blob/3788a522ea81b9b46f10ec97dc63321c7e320824/package.json#L30. 

- [ ] Create a separate unique configuration for ESLint and publish as a stand alone repo (see guide: https://eslint.org/docs/developer-guide/shareable-configs). 
- [ ] Import this repo into our projects or reference in our build-tools, as needed. 
- [ ] Decide on team preferences for prettify and similar (required meeting)
- [ ] Document decisions/recommendations
- [ ] Add a Git commit hook which will run our linting rules and implement these changes in all PB repos where JS code is present. Start with Pressbooks Directory FE.

Related issue: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/85

**Comment by SteelWagstaff** [comment]
Going to close for now.
